services:
  php:
    build: .
    container_name: php
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    # this is for dev in prod this will be removed
    volumes:
      - ./app/about.html:/var/www/html/about.html
      - ./app/help.html:/var/www/html/help.html
      - ./app/database.php:/var/www/html/database.php
      - ./app/google-login.php:/var/www/html/google-login.php
      - ./app/google-callback.php:/var/www/html/google-callback.php
      - ./app/index.php:/var/www/html/index.php
      - ./app/signup.php:/var/www/html/signup.php
      - ./app/login.php:/var/www/html/login.php
      - ./app/dashboard.php:/var/www/html/dashboard.php
      - ./app/navbar.php:/var/www/html/navbar.php
      - ./app/logout.php:/var/www/html/logout.php
    # volumes:
    #   - ./app/:/var/www/html/
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9090:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge