version: '3.8'

services:
  web:
    build: ./
    container_name: runner
    volumes:
      - ./php:/var/www/html
    ports:
      - "9090:80"
    depends_on:
      - composer
      - db
    networks:
      - network_technologies

  composer:
    image: composer:latest
    platform: linux/amd64    
    container_name: di_inter_tech_2025_composer
    volumes:
      - ./php:/app
    working_dir: /app
    command: ["composer", "install"]

  db:
    image: mysql:8.0.28
    platform: linux/amd64    
    container_name: db
    environment:
      - MYSQL_DATABASE=di_internet_technologies_project
      - MYSQL_USER=webuser
      - MYSQL_PASSWORD=webpass
      - MYSQL_ROOT_PASSWORD=rootpass
      - TZ=Europe/Athens
    restart: always
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d/:ro
      - ./database:/var/lib/mysql
    # remove in prod
    ports:
      - "0.0.0.0:3306:3306"
    networks:
      - network_technologies

networks:
  network_technologies:
    name: network_technologies
    driver: bridge
